# Generated by Django 4.0.4 on 2022-05-02 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthead',
            name='total_topup_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='total topup amount'),
        ),
        migrations.AlterField(
            model_name='accounthead',
            name='total_expense_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='total expense amount'),
        ),
        migrations.AlterField(
            model_name='accounthead',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='bill_image',
            field=models.ImageField(blank=True, default='bill.jpeg', null=True, upload_to='bills', verbose_name='bill image'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='accounts.expense', verbose_name='expense'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='unit_price'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='expensetitle',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='topup',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
    ]
