# Generated by Django 4.0.4 on 2022-05-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounthead_total_topup_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthead',
            name='total_expense_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='total expense amount'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='unit_price'),
        ),
        migrations.AlterField(
            model_name='topup',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='amount'),
        ),
    ]
