# Generated by Django 4.0.4 on 2022-05-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounthead_total_expense_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthead',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='remaining amount'),
        ),
        migrations.AlterField(
            model_name='accounthead',
            name='total_topup_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='total topup amount'),
        ),
    ]
