# Generated by Django 4.0.4 on 2022-05-14 12:55

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounthead_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bill_image',
            field=models.ImageField(blank=True, default='bill.jpeg', null=True, upload_to='bills', validators=[accounts.models.validate_image, django.core.validators.FileExtensionValidator(['jpeg', 'png'])], verbose_name='bill image'),
        ),
    ]
